name: wf-cd-production
on:
  push:
    branches:
      - production
jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
      - name: Upload Artifact to GH Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-production"
  deploy-production-job:
    needs: "build-production-job"
    environment: "production-env"
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploye in the Production Environment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-production"
          token: ${{github.token}}        